INSERT [dbo].[Localization_Culture] ([Id], [Name]) VALUES ('fa-IR', N'فارسی')
GO

INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Register',N'ثبت نام کنید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Hello {0}!',N'سلام {0}!','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Log in',N'ورود','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Log off',N'خروج','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'The Email field is required.',N'وارد کردن ایمیل ضروری است.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Email',N'ایمیل','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'User List',N'لیست کاربران','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Remember me?',N'مرا به خاطر داشته باش?','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Password',N'کلمه عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Use a local account to log in.',N'اطلاعات کاربری خود را وارد نمایید.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Register as a new user?',N'ثبت نام کاربر جدید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Forgot your password?',N'کلمه عبور خود را فراموش کردید؟','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Use another service to log in.',N'با استفاده از سرویس‌های دیگر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Full name',N'نام کامل','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Confirm password',N'تکرار کلمه عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create a new account.',N'ساخت اکانت جدید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'All',N'همه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Home',N'خانه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Add to cart',N'اضافه به سبد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Product detail',N'مشخصات محصول','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Product specification',N'ویژگی‌های محصول','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Rate this product',N'به این محصول امتیاز بدهید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Review comment',N'متن','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Review title',N'عنوان','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Posted by',N'پست شده توسط','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Submit review',N'اضافه کردن نظر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'You have',N'دارید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'products in your cart',N'محصولات سبد شما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Continue shopping',N'ادامه خرید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'View cart',N'مشاهده سبد خرید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'The product has been added to your cart',N'محصول به سبد شما اضافه شد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Cart subtotal',N'مجموع','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Shopping Cart',N'سبد خرید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Product',N'محصول','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Price',N'قیمت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Quantity',N'مقدار','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'There are no items in this cart.',N'سبد خرید خالی است.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Go to shopping',N'خرید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Order summary',N'خلاصه سفارش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Subtotal',N'مجموع','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Process to Checkout',N'پایان خرید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Shipping address',N'آدرس تحویل','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Add another address',N'اضافه کردن آدرس جدید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Contact name',N'نام','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Address',N'آدرس','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'State or Province',N'استان','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'District',N'ناحیه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Phone',N'تلفن','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Order',N'سفارش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'products',N'محصولات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'reviews',N'نظرات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Add Review',N'اضافه کردن نظر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Customer reviews',N'نظرات کاربران','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Your review will be shown within the next 24h.',N'نظر شما بعد از بررسی نمایش داده خواهد شد.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Thank you {0} for your review',N'{0} ممنون از نظر ','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Rating average',N'میانگین امتیاز‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'stars',N'امتیازها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Filter by',N'فیلتر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Category',N'دسته','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Brand',N'برند','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Sort by:',N'مرتب سازی:','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'results',N'نتایج','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Users',N'کاربران','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Vendors',N'فروشنده‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Reviews',N'نظرات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Products',N'محصولات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Categories',N'دسته‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Brands',N'برندها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Product Attribute Groups',N'ویژگی‌های محصولات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Product Templates',N'قالب‌های محصولات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Sales',N'فروش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Orders',N'سفارش‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Content Management',N'مدیریت محتوا','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Pages',N'صفحات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Widgets',N'Widgets','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'System',N'سیستم','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Configuration',N'تنظیمات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Translations',N'ترجمه‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Dashboard',N'داشبورد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Incomplete orders',N'سفارشات ناتمام','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Pending reviews',N'نظرات منتظر تایید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Most searched keywords',N'بیشترین جستجوها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Most viewed products',N'بیشنترین مشاهده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'OrderId',N'شناسه سفارش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Order Status',N'وضعیت سفارش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Customer',N'مشتری','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Created On',N'زمان ایجاد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'SubTotal',N'مجموع','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Actions',N'عملیات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Site',N'سایت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Catalog',N'دسته','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Title',N'عنوان','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Comment',N'نظر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Status',N'وضعیت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Rating',N'امتیاز','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Keyword',N'کی‌ورد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Count',N'تعداد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create User',N'ایجاد کاربر جدید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'FullName',N'نام کامل','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Roles',N'نقش‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Edit User',N'ویرایش کاربر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Manager of Vendor',N'مدیر فروشنده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Save',N'ذخیره','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Cancel',N'انصراف','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Phone Number',N'شماره تماس','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create Vendor',N'ایجاد فروشنده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Is Active',N'فعال','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Edit Vendor',N'ویرایش فروشنده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Managers',N'Les مدیران','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Description',N'توضیحات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Pending',N'در انتظار','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Approved',N'تایید شده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Not Approved',N'تایید نشده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Approve',N'تایید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create Product',N'ایجاد محصول','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Is Featured',N'توصیه شده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Is Published',N'پابلیش شده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Yes',N'بله','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'No',N'خیر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Edit Product',N'ویرایش محصول','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Product Name',N'نام محصول','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Short Description',N'توضیح کوتاه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Specification',N'ویژگی‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Old Price',N'قیمت قدیم','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Special Price',N'قیمت ویژه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Thumbnail',N'تصویر کوچک','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Product Images',N'تصویر محصول','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Images',N'تصاویر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Apply',N'اعمال','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Attribute Name',N'نام مشخصه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Value',N'مقدار','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'General Information',N'اطلاعات کلی','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Related Products',N'محصولات مشابه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Manage Related Products',N'مدیریت محصولات مشابه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create Category',N'ایجاد دسته','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Edit Category',N'ویرایش دسته','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create Brand',N'ایجاد برند','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Edit Brand',N'ویرایش برند','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Name',N'نام','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Parent Category',N'دسته پدر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Group',N'گروه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Publish Start',N'شروع پابلیش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Publish End',N'پایان پابلش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Number of Products',N'تعداد محصولات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Order By',N'ترتیب','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Back',N'بازگشت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Change',N'تغییر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Product Information',N'مشخصات محصول','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Application Settings',N'تنظیمات برنامه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create Page',N'ایجاد صفحه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Edit Page',N'ویرایش صفحه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Body',N'بدنه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Edit',N'ویرایش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Security',N'امنیت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create',N'ایجاد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Manage',N'مدیریت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Order History',N'تاریخچه سفارش‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Address Book',N'آدرس‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Add Address',N'اضافه کردن آدرس','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Delete',N'حذف','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Set as default shipping address',N'آدرس پیش فرض','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Edit Address',N'ویرایش آدرس','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Create Address',N'اضافه کردن آدرس','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Your account',N'اکانت شما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Date',N'تاریخ','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Add to Compare',N'مقایسه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Not available',N'در دسترس نیست','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'You save',N'تخفیف شما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Submit',N'ثبت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'All Categories',N'همه دسته‌ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Search here...',N'جستجو...','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Contact',N'تماس','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Cash on Delivery',N'ثبت نهایی سفارش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'New Products',N'محصولات جدید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'About Us',N'درباره ما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Customer comments',N'نوشته ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Recently viewed products',N'محصولاتی که اخیرا مشاهده شدند','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Submiting review is only enable for users who have bought this product',N'ثبت نظر و امتیازدهی فقط برای اشخاصی که کالا را خریده اند، امکان پذیر است و در غیر اینصورت تنها قادر به ثبت کامنت(نوشته) خواهید بود.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Please',N'لطفا','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Login',N'وارد شوید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'or',N'یا','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'to submit your review.',N'برای ثبت نظر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Please also note that submiting review is only enable for users who have bought this product',N' بایستی قبلا کالا را خریداری کرده باشید.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Your comment',N'متن شما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Your comment should not have personal information. 10 - 300 characters:',N'نوشته شما نباید حاوی اطلاعات شخصی باشد و بایستی بین 10 تا حداکثر 300 کاراکتر باشد.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'login',N'وارد شوید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'to reply',N'جهت ثبت اطلاعات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Add Comment',N'ثبت نوشته','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'find by commenter',N'جستجوی متن','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Comments',N'نوشته ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'to submit your questions',N'برای ثبت سوال','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Out Of Stock',N'موجود نمی باشد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Out of stock',N'موجود نمی باشد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Add Reply',N'ثبت پاسخ','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'View all',N'مشاهده همه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Order note',N'توضیحات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Enter order note',N'اگر توضیح خاصی دارد در این قسمت وارد نمایید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Save order note',N'ثبت توضیحات سفارش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Coupon code',N'در صورت داشتن بن تخفیف ، کد را در این قسمت وارد نمایید و اعمال را بزنید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Enter coupon',N'کد تخفیف','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Discount',N'تخفیف','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Order Total',N'مبلغ نهایی','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Shipping',N'حمل و نقل','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Tax',N'مالیات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Shipping methods',N'حمل و نقل','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Billing Address',N'ارسال فاکتور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Use Selected Shipping Address As Billing Address',N'فاکتور به همراه کالاها ارسال شود.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Payment',N'پرداخت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Cancel Order',N'لغو سفارش','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Choose a payment methods',N'نحوه پرداخت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'INVOICE',N'فاکتور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Congratulation!',N'تبریک','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Your order',N'سفارش شما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'has been received. Thank you',N'با موفقیت ثبت شد. باتشکر از خرید شما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Account Dashboard',N'حساب کاربری','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Account Information',N'اطلاعات کاربری','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Sécurité',N'امنیت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'External Logins',N'ورود با سرویس های دیگر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Default shipping address',N'آدرس پیشفرض شما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Manage address',N'مدیریت آدرس ها','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'My Settings',N'تنظیمات من','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Wish List',N'کالاهای مورد علاقه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Change Password Form',N'تغییر رمز عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Change password',N'ثبت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Manage your external logins',N'ورود با سرویس های دیگر خود را مدیریت کنید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Registered Logins',N'سرویس های ذخیره شده','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Add another service to log in.',N'سرویس جدیدی را برای ورود اضافه کنید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'register',N'ثبت نام کنید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'There are currently no items in your wish list',N'هنوز هیچ کالایی در لیست علاقه مندی شما ثبت نشده است.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Compare',N'مقایسه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'compare',N'مقایسه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Compare products',N'مقایسه محصولات','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Remove',N'حذف','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'remove',N'حذف','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'There is no product to compare',N'محصولی برای مقایسه وجود ندارد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Association Form',N'فرم تایید ورود با سرویس های اینترنتی','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Please enter an email address for this site below and click the Register button to finish logging in.',N'لطفا ایمیل و نام خود را برای استفاده در این سایت در قسمت زیر وارد نمایید و دکمه ثبت نام را بزنید.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Login Failure',N'ورود با خطا مواجه شد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Unsuccessful login with service.',N'متاسفانه ورود با سرویس دیگر انجام نشد.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Result',N'نتيجه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Shipping Information',N'اطلاعات آدرس','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Payment Information',N'اطلاعات پرداخت','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Search',N'جستجو','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Contact Us',N'تماس با ما','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Home Page',N'خانه','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Access Denied',N'دسترسي غيرمجاز','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'We are sorry!',N'متاسفيم!','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Permission is needed to access the page.',N'شما مجوز دسترسي به اين صفحه را نداريد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Confirm Email',N'تاييد ايميل','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Thank you for confirming your email.',N'ايميل شما با موفقيت تاييد شد ، باتشکر.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Click here to Log in',N'براي ورود اينجا کليک کنيد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Forgot Password Confirmation',N'تاييد فراموشي رمز عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Please check your email to reset your password.',N'لطفا ايميل خود را جهت تغيير رمز عبور چک کنيد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Locked out',N'قفل شدن حساب کاربري','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'This account has been locked out, please try again later.',N'اين حساب کاربري قفل شده است ، لطفا بعدا تلاش کنيد','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Reset password',N'تغییر رمز عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Reset',N'تغییر','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Reset password confirmation',N'تایید تغییر رمز عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Your password has been reset.',N'رمز عبور شما تغییر کرد.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Send Verification Code',N'ارسال کد شناسایی','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Select Two-Factor Authentication Provider:',N'انتخاب سرویس ورود به سیستم دو مرحله ای:','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Verify',N'شناسایی','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Change Password',N'تغییر کلمه عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Manage your account',N'مدیریت حساب کاربری','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Set Password',N'ثبت کلمه عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'You do not have a local username/password for this site. Add a local account so you can log in without an external login.',N'شما در این وب سایت حساب کاربری محلی ندارید ، لطفا یک حساب محلی ایجاد کنید تا بتوانید بدون استفاده از سرویس های دیگر مانند گوگل و فیس بوک ، به سایت ورود کنید.','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Set password',N'ثبت کلمه عبور','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Set your password',N'کلمه عبور خود را ثبت کنید','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'News',N'اخبار','fa-IR')
INSERT [dbo].[Localization_Resource] ([Key], [Value], [CultureId]) VALUES ( N'Notifications',N'اعلان ها','fa-IR')
GO